import = [
  "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[font]
size = 14

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[env]
TERM = 'xterm-256color'
