export const recordTypeConstants = {

  // record-types
  LOGIN : "login",
  BANK_CARD: "bankCard",
  BANK_ACCOUNT: "bankAccount",
  ADDRESS: "address",
  CONTACT: "contact",
  ENCRYPTED_NOTES: "encryptedNotes",
  DRIVER_LICENSE: "driverLicense",
  PASSPORT: "passport",
  SOCIAL_SECURITY_CARD: "ssnCard",
  HEALTH_INSURANCE: "healthInsurance",
  MEMBERSHIP: "membership",
  BIRTH_CERTIFICATE: "birthCertificate",
  DATABASE_CREDENTIALS: "databaseCredentials", // to-do: confirm name
  SERVER_CREDENTIALS: "serverCredentials",
  SSH_KEYS: "sshKeys",
  SOFTWARE_LICENSE: "softwareLicense",

  // fields
  TITLE: "title",
  LOGO: "logo",
  PASSWORD: "password",
  NAME: "name",
  COMPANY: "company",
  PHONE: "phone",
  EMAIL: "email",
  CONTACT_PHONE: "contact",
  CONTACT_EMAIL: "contactEmail",
  ADDRESS_REF: "addressRef",
  CARD_NUMBER: "cardNumber",
  DATE: "date",
  BIRTH_DATE: "birthDate",
  EXPIRATION_DATE: "expirationDate",
  CARD_EXPIRATION_DATE: "cardExpirationDate",
  CARD_SECURITY_CODE: "cardSecurityCode",
  ACCOUNT_NUMBER: "accountNumber",
  GROUP_NUMBER: "groupNumber",
  CARD_REF: "cardRef",
  NOTE: "note",
  URL: "url",
  PHOTO: "photo",
  FILE: "file",
  FILE_REF: "fileRef",
  HOST: "host",
  SECURITY_QUESTION: "securityQuestion",
  PIN_CODE: "pinCode",
  ONE_TIME_CODE: "oneTimeCode",
  PRIVATE_KEY: "privateKey",
  MNEUMONIC: "mnuemonic",

  // field-types
  ACCOUNT_TYPE: "accountType",
  ROUTING_NUMBER: "routingNumber",
  FULL_NAME: "fullName",
  FIRST_NAME: "firstName",
  LAST_NAME: "lastName",
  STREET_1: "street1",
  STREET_2: "street2",
  CITY: "city",
  STATE: "state",
  ZIP: "zip",
  COUNTRY: "country"

}